# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auvs0Ac4IZOtN0nOXwHqOLdJFm3VyIEc
"""

import requests
import json

api_url = 'https://jsonplaceholder.typicode.com/todos'
response = requests.get(api_url)
print(response)

data = response.json()
print(data)

for todo in data:
  if todo['completed'] == True:
    json_obj = json.dumps(todo, indent=4)
    print(json_obj)

from datetime import date

today = date.today()

url = f'https://api.myquran.com/v2/sholat/jadwal/1203/{today}'
response = requests.get(url)
data = response.json()

print(f"Jadwal Shalat Kab. Bekasi {today}")
data = data['data']['jadwal']
for key in data.keys():
  print(f"{key} : {data[key]}")

